# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:35
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import musicdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0004_auto_20151211_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='/mnt/lossless/', recursive=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/musicdb/media/', location=b'/mnt/lossless/'), upload_to=musicdb.models.cover_location),
        ),
        migrations.AlterField(
            model_name='track',
            name='path',
            field=models.FilePathField(blank=True, match='.*\\.flac$', null=True, path='/mnt/lossless/', recursive=True),
        ),
    ]
