# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 10:20
from __future__ import unicode_literals

from django.db import migrations


def set_path(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Track = apps.get_model("musicdb", "Track")
    for track in Track.objects.all():
        if track.uri:
            track.path = track.uri.replace(track.album.path+'/', '')
            track.save()


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0005_auto_20151227_1535'),
    ]

    operations = [
        migrations.RunPython(set_path),
        migrations.RemoveField(
            model_name='track',
            name='uri',
        ),
    ]
