# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0006_auto_20151227_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
