# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0007_auto_20151228_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='musicdb.Genre'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='musicdb.Label'),
        ),
    ]
