# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0008_auto_20160103_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ManyToManyField(to='musicdb.Label'),
        ),
    ]
