# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0010_auto_20160103_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
