# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def move_data(apps, schema_editor):
    Album = apps.get_model("musicdb", "Album")
    Release = apps.get_model("musicdb", "Release")
    for album in Album.objects.all():
        if album.label:
            for label in album.label.all():
                release = Release(
                        label=label,
                        catalog_num=album.catalog_num, album=album)
                release.save()


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0011_auto_20160120_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('catalog_num', models.CharField(
                    blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='album',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='musicdb.Album'),
        ),
        migrations.AddField(
            model_name='release',
            name='label',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='musicdb.Label'),
        ),
        migrations.RunPython(move_data),
        migrations.AddField(
            model_name='album',
            name='labels',
            field=models.ManyToManyField(
                blank=True, through='musicdb.Release', to='musicdb.Label'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='catalog_num',
        ),
        migrations.RemoveField(
            model_name='album',
            name='label',
        ),
    ]
