# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 18:17
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import musicdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0012_many_catalog_numbers_and_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='cover',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/musicdb/media/', location=b'/mnt/lossless/'), upload_to=musicdb.models.cover_location),
        ),
        migrations.AlterField(
            model_name='cover',
            name='covertype',
            field=models.CharField(choices=[('back_out', 'back out'), ('front_out', 'front out'), ('back_in', 'back in'), ('front_in', 'front in'), ('disc', 'disc'), ('in', 'in'), ('out', 'out'), ('booklet', 'booklet'), ('other', 'other')], default='front_out', max_length=10),
        ),
    ]
