# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0013_auto_20160227_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True, path='/mnt/lossless/', recursive=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='rg_gain',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='rg_peak',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
