# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0015_auto_20160306_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='album',
            name='edition_title',
            field=models.CharField(default='Original Release', max_length=256, null=True),
        ),
    ]
