# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0016_auto_20160316_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
