# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0017_auto_20160316_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
