# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0018_auto_20160316_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
